# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Colistador For Driver' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Colistador For Driver
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

  target 'Colistador For DriverTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Colistador For DriverUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
